// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_level`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// FR-01, FR-02, FR-03, FR-05 — định dạng đầu ra suy ra từ đuôi mở rộng của `dest`.
Future<void> compressFiles({
  required List<String> sources,
  required String dest,
  String? password,
  String? level,
}) => RustLib.instance.api.crateApiSimpleCompressFiles(
  sources: sources,
  dest: dest,
  password: password,
  level: level,
);

/// FR-10, FR-11.
Future<void> extractArchive({
  required String archive,
  required String destDir,
  String? password,
}) => RustLib.instance.api.crateApiSimpleExtractArchive(
  archive: archive,
  destDir: destDir,
  password: password,
);

/// FR-12 — xem trước nội dung mà không giải nén toàn bộ.
Future<List<EntryInfo>> listArchiveEntries({
  required String archive,
  String? password,
}) => RustLib.instance.api.crateApiSimpleListArchiveEntries(
  archive: archive,
  password: password,
);

/// FR-16 — Test Archive.
Future<bool> testArchiveIntegrity({
  required String archive,
  String? password,
}) => RustLib.instance.api.crateApiSimpleTestArchiveIntegrity(
  archive: archive,
  password: password,
);

/// FR-04 — chia 1 file thành nhiều phần theo kích thước MB. Trả về đường dẫn các phần
/// theo thứ tự.
Future<List<String>> splitFile({
  required String file,
  required BigInt sizeMb,
}) => RustLib.instance.api.crateApiSimpleSplitFile(file: file, sizeMb: sizeMb);

/// FR-04 — ghép các phần đã chia (bắt đầu từ phần `.001`) lại thành 1 file.
Future<void> joinParts({required String firstPart, required String dest}) =>
    RustLib.instance.api.crateApiSimpleJoinParts(
      firstPart: firstPart,
      dest: dest,
    );

/// FR-18/19 — thêm file/thư mục vào 1 file .zip đã có sẵn, không nén lại từ đầu.
Future<void> addArchiveEntries({
  required String archive,
  required List<String> sources,
  String? password,
  String? level,
}) => RustLib.instance.api.crateApiSimpleAddArchiveEntries(
  archive: archive,
  sources: sources,
  password: password,
  level: level,
);

/// FR-18/19 — xoá các entry có tên khớp `names` khỏi 1 file .zip.
Future<void> removeArchiveEntries({
  required String archive,
  required List<String> names,
}) => RustLib.instance.api.crateApiSimpleRemoveArchiveEntries(
  archive: archive,
  names: names,
);

/// Bản sao của `vietzip_core::EntryInfo` sang kiểu mà flutter_rust_bridge sinh mã Dart
/// được (frb không thể trực tiếp expose struct từ crate ngoài).
class EntryInfo {
  final String name;
  final BigInt size;
  final bool isDir;

  const EntryInfo({
    required this.name,
    required this.size,
    required this.isDir,
  });

  @override
  int get hashCode => name.hashCode ^ size.hashCode ^ isDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          size == other.size &&
          isDir == other.isDir;
}
